ref: rules and faq
NotANameServer/discord pull request #19
Opened 2021-04-27 00:34 UTC by Julien00859

The rules of NaN are split between two channels: #regles and #faq. The
\#regle channel just list 8 rules that are commonly found on discord
servers : be nice to other, spell correctly, don't send ads, etc. The
\#faq channel lists various situation the newbies can find themselves in
and explain how to correctly behave in those situations.

The problem is that the #regle channel doesn't only states rules: it
also explain how things like the :modo: flag works. Same goes for the
\#faq channel, some of the "how to behave" sitation are rules de facto.

We argue that the two channels should be merged into one into a rule book
that both list rules and explain how the server works.

We identified 4 categories:

1/ The rules, classic set of rules common with a lot a discord servers.
2/ How the server works, how to join channels, what channels are for,
   how to ask for help, etc.
3/ The moderated channels: #offre, #vos-projets, #lives.
4/ Some meta informations about the server like how to suggest changes.

By merging all the rules in one place, we had the opportunity to
carefully reword every sentence so it better reflects the server as it
is in 2021.

Co-authored-by: Lezenn <51204940+GiregL@users.noreply.github.com>
Closes #13

2021-04-27 01:40 UTC, LeMinaw requested changes

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +personne ne vous répond c'est que personne de connecté n'est compétente sur
_c'est **qu'aucune** personne connectée n'est compétente..._

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +aides concernant le langage python. Le canal #bots-discord quand à lui sera
quan**t** à lui

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +Les ambassadeurs sont des membres habitués qui font un travaille de fond dans
trava**il**

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +le salon technique duquel ils sont ambassadeurs. Ils assurent la pérénité des
-duquel +dont

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +  règles.
_tout abus sera puni_, non ?

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +
Règle concernant les mises à jour / repost ?

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +Le salon #offres permet de poster des offres d'emploi au sain de notre
s**e**in

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +pour ne pas notifier les membres lorsque vous faites un live sur un sujet tier.
tier**s**

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +~~Beaucoup de questions redondantes sont oosées chaques jours sur le serveur.
**p**osées

2021-04-27 01:40 UTC, LeMinaw commented on regles.md
> +ajouter une commande, ...) en soumettant une pull request avec votre
pull request ou issue il me semble ?

2021-04-27 01:46 UTC, GuillaumeBelz reviewed
Juste un test

2021-04-27 01:46 UTC, GuillaumeBelz commented on regles.md
> +Les ambassadeurs sont des membres habitués qui font un travaille de fond dans
```suggestion
Les ambassadeurs sont des membres habitués qui font un travail de fond dans
```

2021-04-27 01:49 UTC, Julien00859 commented on regles.md
> +  règles.
J'ai mis "merci de ne pas en abuser"

2021-04-27 01:50 UTC, Julien00859 commented on regles.md
> +
on est déjà assez actif sur la modération du contenu dans screenshot et ya le time limit, c'est un salon facile à modérer, je pense pas qu'on a besoin de le préciser, c'est dans la description du salon

2021-04-27 01:52 UTC, Mesteery requested changes

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Not a Rule Book**
```suggestion
# Not a Rule Book
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**~ ~ ~ Règlement ~ ~ ~**
```suggestion
## Règlement
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +1. Le respect des autres membres du serveur est une priorité. Vous soignez vos
```suggestion
1. Le respect des autres membres du serveur est une priorité. Vous devez soignez vos
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +2. La loi française est d'application sur le serveur. Les contenus illégaux, le
```suggestion
2. La loi française est appliquée sur le serveur. Les contenus illégaux, le
```
C'est ça que tu voulais dire ?

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   piratage, la pornographie, le gore, etc sont interdits. Plus précisément,
```suggestion
   piratage, la pornographie, le gore, etc. sont interdits. Plus précisément,
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   les sujets borderlines, ceux à la légalité douteuse ou dont l'usage n'est
```suggestion
   les sujets limites, ceux à la légalité douteuse ou dont l'usage n'est
```
On pourrait éviter le franglais, non ?

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   aux discussions diverses (#discussions et #detente), c'est pour que les
```suggestion
   aux discussions diverses (`#discussions` et `#detente`), c'est pour que les
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +La 1e règle du serveur est essentielle au maintient d'une ambiance propice au
```suggestion
La première règle du serveur est essentielle au maintient d'une ambiance propice au
```
Ou 1ère

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**~ ~ ~ Moeurs ~ ~ ~**
```suggestion
## Moeurs
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Les salons**
```suggestion
### Les canaux
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   sont soumis à une règlementation accrue. Il existe des salons dédiés à ces
```suggestion
   sont soumis à une règlementation accrue. Il existe des canaux dédiés à ces
```
Je pense qu'on peut utiliser le même mot, canal, dans tout ce document.

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   messages et l'accès à ses salons est modéré par le staff. Tout message à
```suggestion
   messages et l'accès à ses canaux est modéré par le staff. Tout message à
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   tendance publicitaire ou de recrutement envoyé en dehors de ces salons ou
```suggestion
   tendance publicitaire ou de recrutement envoyé en dehors de ces canaux ou
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +6. Le serveur se veut dans l'ensemble sérieux, si il existe des salons prévus
```suggestion
6. Le serveur se veut dans l'ensemble sérieux, s'il existe des canaux prévus
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   autres salons puissent rester centrés sur leur domaines.
```suggestion
   autres canaux puissent rester centrés sur leur domaines.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +La plupart des salons sont invisibles, vous pouvez rejoindre les différents
```suggestion
La plupart des canaux sont invisibles, vous pouvez rejoindre les différents
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +salons via le menu #rejoindre-les-canaux.
```suggestion
canaux via le menu présent dans `#rejoindre-les-canaux`.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Pensez à lire la description et les messages épinglés des différents salons que
```suggestion
Pensez à lire la description et les messages épinglés des différents canaux que
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +vous rejoignez. Ils précisent le sens de leurs salons et apportent des
```suggestion
vous rejoignez. Ils précisent le sens de leurs canaux et apportent des
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +informations souvent importantes (ressources, cours, etc).
```suggestion
informations souvent importantes (ressources, cours, conseils, etc.).
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Si vous comptez rejoindre un salon pour demander de l'aide, merci de donner un
```suggestion
Si vous comptez rejoindre un canal pour demander de l'aide, merci de donner un
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +votre erreur, ... Tout ceci permettera aux autres membres de mieux comprendre
```suggestion
votre erreur, etc. Tout ceci permettera aux autres membres de mieux comprendre
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +personne ne vous répond c'est que personne de connecté n'est compétente sur
```suggestion
personne ne vous répond c'est que personne de connecté n'est compétent sur
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Les salons sérieux**
```suggestion
### Les salons sérieux
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Les salons sérieux portent le nom et la description de la technologie ou du
```suggestion
Les salons canaux portent le nom et la description de la technologie ou du
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +sujet auxquels ils sont dédié. Par exemple, le canal #python sera dédié aux
```suggestion
sujet auxquels ils sont dédié. Par exemple, le canal `#python` sera dédié aux
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +aides concernant le langage python. Le canal #bots-discord quand à lui sera
```suggestion
aides concernant le langage Python. Le canal `#bots-discord` quant à lui sera
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +dédié à la création de bots discord, quel que soit le langage.
```suggestion
dédié à la création de bots Discord, quel que soit le langage.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Toutes les sections *Technologies*, *Languages*, *Rendu 3D* ainsi que les
```suggestion
Les catégories *Technologies*, *Languages*, *Rendu 3D* ainsi que les
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +salons #infographie, #sciences, #etudes et #questions-professionnelles sont des
```suggestion
canaux `#infographie`, `#sciences`, `#etudes` et `#questions-professionnelles` sont des
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +salons sérieux.
```suggestion
canaux sérieux.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Les salons où les discussions hors-sujet sont les bienvenues sont #discussions
```suggestion
Les canaux où les discussions hors-sujet sont les bienvenues dans `#discussions`
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +et #detente.
```suggestion
et `#detente`.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**L'aide en MP (messages privés)**
```suggestion
### L'aide en messages privés (MP)
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**L'aide en vocal**
```suggestion
### L'aide en vocal
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +dans un canal technique ou #discussions de venir en vocal sera généralement
```suggestion
dans un canal technique ou `#discussions° de venir en vocal sera généralement
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Les ambassadeurs**
```suggestion
### Les ambassadeurs
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +le salon technique duquel ils sont ambassadeurs. Ils assurent la pérénité des
```suggestion
le canal technique duquel ils sont ambassadeurs. Ils assurent la pérénité des
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +échanges, animent leurs salons et servent de pont avec le staff. Ils sont
```suggestion
échanges, animent leurs canaux et servent de pont avec le staff. Ils sont
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Les réactions utiles**
```suggestion
### Les réactions utiles
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- :lourd: : Utilisé pour désigner un message lourd dans une conversation
Faudrait mettre une image à la place (je link ça demain)

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- :bell: : Utilisé pour indiquer aux autre quand vous voulez être ping quand on
```suggestion
- :bellhop_bell: : Utilisé pour indiquer aux autres que vous voulez être mentionné quand on
```
En général c'est 🛎 au lieu de 🔔

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- :arrow\_double\_up: : Indique que la réponse à votre question se trouve un
```suggestion
- :arrow_double_up: : Indique que la réponse à votre question se trouve un
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +  automatiquement épinglé au bout de 10 réactions.
Je crois que cette option n'est pas activée que NaN

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- :modo: : Sert à prévenir les modérateurs qu'un message transgresse les
Same : mettre une image, je link ça demain

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- :modo: : Sert à prévenir les modérateurs qu'un message transgresse les
```suggestion
- :modo: : Sert à prévenir le staff qu'un message transgresse les
```
Le staff même, non ?

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Poster du code**
```suggestion
### Poster du code
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +[F.A.Q.](https://discord.com/channels/323076998576603137/699260551758610545/712619259599126569)
Pas moyen de quand même mettre ça ici ?

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- <https://paste.artemix.org>
```suggestion
- https://paste.artemix.org/
```
Pour rester cohérent avec le prochain lien

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +- <https://bin.readthedocs.fr/>
```suggestion
- https://bin.readthedocs.fr/
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**~ ~ ~ Salons Modérés ~ ~ ~**
```suggestion
## Les canaux modérés
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Suite à de *très* (*très*) nombreux abus passés, comme repris par la 3e règle,
```suggestion
Suite à de *très* nombreux abus passés, comme repris par la troisième règle,
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +projets se font uniquement dans leurs salons respectifs et sous réserve de
```suggestion
projets se font uniquement dans leurs canaux respectifs et sous réserve de
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +l'approbation du staff. Contactez le staff via un ticket `!newticket`.
Faudrait pas plutot une section `### Contacter le staff` et ici mettre un `*[Voir section ...](#Contacter-le-staff)*` ?

EDIT: j'ai vu que cette section existe, il manque plus qu'à la link

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**#vos-projets**
```suggestion
### `#vos-projets`
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Le salon #vos-projets est réservé à l'exposition de vos créations en rapport
```suggestion
Le canal `#vos-projets` est réservé à l'exposition de vos créations en rapport
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +avec les axes du serveur (développement, infographie, sciences, ...). Un état
```suggestion
avec les axes du serveur (développement, infographie, sciences, etc.). Un état
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +projets secrets et les serveurs de jeux n'ont pas leur place dans NaN. Pour les
```suggestion
projets secrets et les serveurs de jeux n'ont pas leur place sur Not A Name. Pour les
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +petites créations, vous pouvez toujours passer par le salon #screenshot.
```suggestion
petites créations, vous pouvez toujours passer par le canal `#screenshots`.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**#offres**
```suggestion
### `#offres`
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Le salon #offres permet de poster des offres d'emploi au sain de notre
```suggestion
Le canal `#offres` permet de poster des offres d'emploi au sain de notre
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**#live**
```suggestion
### `#live`
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Le salon #live vous donne la possibilité de publier vos annonces de live
```suggestion
Le canal `#live` vous donne la possibilité de publier vos annonces de live
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +twitch/youtube sur les sujets dans l'axe du serveur. Nous attendons une
```suggestion
Twitch/YouTube sur les sujets dans l'axe du serveur. Nous attendons une
```
Btw un peu bizarre comme phrase

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +~~**La F.A.Q.**~~
```suggestion
## La F.A.Q.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +~~Beaucoup de questions redondantes sont oosées chaques jours sur le serveur.
```suggestion
Beaucoup de questions redondantes sont osées chaque jour sur le serveur.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Afin d'y répondre au maximum nous avons un canal #faq. Ce dernier liste les
```suggestion
Afin d'y répondre au maximum nous avons un canal `#faq`. Ce dernier liste les
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +`!mp`, `!ask` ou autre.~~
```suggestion
`!mp`, `!ask` ou autre.
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**~ ~ ~ Le serveur ~ ~ ~**
```suggestion
## Le serveur
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Le GitHub**
```suggestion
### Le GitHub
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +ajouter une commande, ...) en soumettant une pull request avec votre
```suggestion
ajouter une commande, etc.) en soumettant une Pull Request avec votre
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Github](https://github.com/NotANameServer/discord)
```suggestion
GitHub](https://github.com/NotANameServer/discord).
```
Le lien est cassé avec le saut de ligne ou pzs ?

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +**Contacter le staff**
```suggestion
### Contacter le staff
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +Le staff peut être contacté par un système de tickets via la commande
```suggestion
Le staff peut être contacté par le système de ticket via la commande
```

2021-04-27 01:52 UTC, Mesteery commented on regles.md
> +   par MP est interdit. Voir la section *Les salons modérés*.
```suggestion
   par message privé est interdit. *[Voir la section **Les canaux modérés**](#Les-canaux-modérés)*.
```

2021-04-27 08:18 UTC, SirLynix commented
Je ne suis pas sûr de l'intérêt de taper la discute en anglais ici. 😄

2021-04-27 08:31 UTC, GiregL commented
Mesteery,
Les titres étaient en gras pour coller au format des messages Discord, pas pour le format markdown du dépôt. Le but étant de mettre le rule book directement formaté dans le canal des règles.

2021-04-27 08:32 UTC, SirLynix commented
> Le but étant de mettre le rule book directement formaté dans le canal des règles.

Alors ça je maintiens que c'est une *très* mauvaise idée #13

2021-04-27 08:55 UTC, SirLynix commented on regles.md
> +1. Le respect des autres membres du serveur est une priorité. Vous soignez vos
Devez soigner* du coup.

Personnellement je n'aime pas du tout cette formulation, ça fait beaucoup trop soutenu, à la limite hautain.

2021-04-27 08:59 UTC, SirLynix commented
Pour rebondir sur la discussion dans #13, je pense que ce serait une bonne idée de garder un canal #règles clair et concis (avec des embed par NaB en prime pour rendre ça plus lisible ?) et de remplacer #faq par le #rule-book (en le rendant plus complet et en le découpant en sections, comme pour la FAQ, on pourra y glisser un sommaire du coup).

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Not a Rule Book**
Le but du repo github est de refléter la configuration discord, être un mirroir précis qu'on puisse copier/coller d'un côté comme de l'autre. Nous ne prévoyons pas d'utiliser github comme un endroit pour visualiser les différents document, nous utilisons uniquement la plateforme comme un moyen collaboratif pour faire évoluer la configuration du serveur. Le markdown sémantique, bien que plus beau, plus adapté pour github, n'est pas compatible avec discord. Si nous acceptons de changer le document pour utiliser du markdown sémantique, nous devrons systématiquement retravailler le document avant de le publier sur discord, c'est du travail supplémenaite que je juge inutile et error-prone.

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**~ ~ ~ Règlement ~ ~ ~**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +   les sujets borderlines, ceux à la légalité douteuse ou dont l'usage n'est
On utilise déjà la commande !borderline, je ne vois pas en quoi la formulation est choquante

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +   sont soumis à une règlementation accrue. Il existe des salons dédiés à ces
On avait décidé de l'inverse : utiliser "salon" dans tout le document.

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +   messages et l'accès à ses salons est modéré par le staff. Tout message à
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +2. La loi française est d'application sur le serveur. Les contenus illégaux, le
Oui, "est d'application" est mieux IMO

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +   tendance publicitaire ou de recrutement envoyé en dehors de ces salons ou
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +6. Le serveur se veut dans l'ensemble sérieux, si il existe des salons prévus
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +   aux discussions diverses (#discussions et #detente), c'est pour que les
Pareil que l'argument du markdown sémantique, on compte copier/coller, les salons doivent être un lien vers le salon existant, je dois encore vérifier que simplement écrire #detente suffit à avoir le lien sinon on devra mettre le lien du salon. Dans tous les cas, une balise code n'a pas sa place ici

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +La 1e règle du serveur est essentielle au maintient d'une ambiance propice au
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Les salons**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +salons via le menu #rejoindre-les-canaux.
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +Pensez à lire la description et les messages épinglés des différents salons que
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +vous rejoignez. Ils précisent le sens de leurs salons et apportent des
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Les salons sérieux**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +Les salons sérieux portent le nom et la description de la technologie ou du
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +sujet auxquels ils sont dédié. Par exemple, le canal #python sera dédié aux
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +salons #infographie, #sciences, #etudes et #questions-professionnelles sont des
:arrow_double_up: :arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +salons sérieux.
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +et #detente.
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**L'aide en vocal**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +dans un canal technique ou #discussions de venir en vocal sera généralement
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Les ambassadeurs**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +échanges, animent leurs salons et servent de pont avec le staff. Ils sont
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Les réactions utiles**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +  automatiquement épinglé au bout de 10 réactions.
Sisi

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Poster du code**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +- :lourd: : Utilisé pour désigner un message lourd dans une conversation
Pareil que le reste, on veut pouvoir copier/coller, une image n'irait pas

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +- :modo: : Sert à prévenir les modérateurs qu'un message transgresse les
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +- <https://paste.artemix.org>
Pareil que le reste, github vs discord, discord a la priorité

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +- <https://bin.readthedocs.fr/>
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**~ ~ ~ Salons Modérés ~ ~ ~**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +projets se font uniquement dans leurs salons respectifs et sous réserve de
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**#vos-projets**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +Le salon #vos-projets est réservé à l'exposition de vos créations en rapport
:arrow_double_up: :arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +petites créations, vous pouvez toujours passer par le salon #screenshot.
:arrow_double_up: :arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**#offres**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**#live**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +Le salon #live vous donne la possibilité de publier vos annonces de live
:arrow_double_up: :arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +~~**La F.A.Q.**~~
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +Afin d'y répondre au maximum nous avons un canal #faq. Ce dernier liste les
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +`!mp`, `!ask` ou autre.~~
(en fait on propose de retirer ce message, d'où le fait qu'il est barré pour le moment)

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**~ ~ ~ Le serveur ~ ~ ~**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Le GitHub**
:arrow_double_up:

2021-04-27 09:28 UTC, Julien00859 commented on regles.md
> +**Contacter le staff**
:arrow_double_up:

2021-04-27 11:11 UTC, Mesteery commented on regles.md
> +   aux discussions diverses (#discussions et #detente), c'est pour que les
Pour le GitHub si, c'est plus facile à lire. Et dans tous les cas, ça passera pas comme ça sur Discord tu verras bien.

2021-04-27 11:18 UTC, Mesteery commented
> Le but du repo github est de refléter la configuration discord, être un mirroir précis qu'on puisse copier/coller d'un côté comme de l'autre. Nous ne prévoyons pas d'utiliser github comme un endroit pour visualiser les différents document, nous utilisons uniquement la plateforme comme un moyen collaboratif pour faire évoluer la configuration du serveur. Le markdown sémantique, bien que plus beau, plus adapté pour github, n'est pas compatible avec discord. Si nous acceptons de changer le document pour utiliser du markdown sémantique, nous devrons systématiquement retravailler le document avant de le publier sur discord, c'est du travail supplémenaite que je juge inutile et error-prone.

Ça, comme je l'ai répété une vingtaine de fois sur Discord, je suis pas d'accord. On va arrêter de priver des fonctionnalités supplémentaires juste pour Discord. Je rappelle également que c'est seulement les titres qui sont à changé. Le pire de tout ça, c'est que tous les canaux mentionnés ici ne marcheront pas sur Discord.
Donc l'argument tient pas.
Sinon, une idée évoquée, c'était de faire une petite GitHub Action qui se chargerait de rendre chaque Markdown du repo Discord-compatible et qui mettrait les résultats dans un dossier du genre `build`, ou bien une branche dédiée.

2021-04-27 11:21 UTC, Mesteery commented
> On avait décidé de l'inverse : utiliser "salon" dans tout le document.
Ah ouai, il me semblait le contraire. Surtout que `canal` est utilisé plusieurs fois dans cette PR même mais également sur tous les autres documents ici et sur challenges. Mais également partout sur le Discord.

2021-04-27 11:23 UTC, Mesteery commented on regles.md
> +La 1e règle du serveur est essentielle au maintient d'une ambiance propice au
Là j'ai pas compris pourquoi... ?

2021-04-27 11:24 UTC, Mesteery commented on regles.md
> +6. Le serveur se veut dans l'ensemble sérieux, si il existe des salons prévus
Et s'il ?

2021-04-27 11:25 UTC, Mesteery commented on regles.md
> +salons via le menu #rejoindre-les-canaux.
Le canal même s'appelle "#rejoindre-les-canaux" alors pourquoi dire salon dans tous le document ?

2021-04-27 11:25 UTC, Mesteery commented on regles.md
> +votre erreur, ... Tout ceci permettera aux autres membres de mieux comprendre
^

2021-04-27 11:26 UTC, Mesteery commented on regles.md
> +dédié à la création de bots discord, quel que soit le langage.
^^^

2021-04-27 11:26 UTC, Mesteery commented on regles.md
> +Toutes les sections *Technologies*, *Languages*, *Rendu 3D* ainsi que les
^^&

2021-04-27 11:28 UTC, Mesteery commented on regles.md
> +- :lourd: : Utilisé pour désigner un message lourd dans une conversation
J'y est pas pensé. 
Dans tous les cas ça va avec mon commentaire d'en bas. Avec une Action on pourrait **arrêter** de se limiter à Discord... !
Je vois vraiment pas ce qui te fais peu la dedans.

2021-04-27 11:29 UTC, Mesteery commented on regles.md
> +- :bell: : Utilisé pour indiquer aux autre quand vous voulez être ping quand on
^^

2021-04-27 11:29 UTC, Mesteery commented on regles.md
> +- :arrow\_double\_up: : Indique que la réponse à votre question se trouve un
^^

2021-04-27 11:29 UTC, Mesteery commented on regles.md
> +  automatiquement épinglé au bout de 10 réactions.
Ah ouai ?

2021-04-27 11:30 UTC, Mesteery commented on regles.md
> +- :modo: : Sert à prévenir les modérateurs qu'un message transgresse les
^^ comme pour tous les commentaires dau dessus c'est dur pour me de savoir pourquoi c'est resolved sans aucun commentaire ou que c'est même pas appliqué...

2021-04-27 11:31 UTC, Mesteery commented on regles.md
> +- <https://paste.artemix.org>
Et le `/` s'envole ?

2021-04-27 11:31 UTC, SirLynix commented on regles.md
> +- :lourd: : Utilisé pour désigner un message lourd dans une conversation
Ah ben après si quelqu'un est chaud pour faire un petit script qui transforme le .md version GH en un markdown pratique sur Discord, pourquoi pas.

2021-04-27 11:32 UTC, Mesteery commented on regles.md
> +petites créations, vous pouvez toujours passer par le salon #screenshot.
Manque le s

2021-04-27 11:40 UTC, Mesteery commented on regles.md
> +- :lourd: : Utilisé pour désigner un message lourd dans une conversation
Le truc c'est que ça me dérange pas du tout et j'ai dit et j'ai répété que je le ferais. Mais Lazor a pas aimé cette idée. Il veut vraiment avoir un truc à la lettre pris sur GitHub et sur Discord (ce qui n'est actuellement pas du tout le cas dans ce repo ou même dans cette PR...).

2021-04-27 11:46 UTC, Julien00859 commented
> 1. tous ces sauts de lignes pour respecter une ligne width ne seront pas rendu sur GitHub comme sur Discord (sur GitHub ce sera une ligne entière qui prend toute l'écran contrairement à Discord où ça restera découpé comme ici peut importe la taille de l'écran...), étalement je t'assure que ça dépasse mes 2000 caractères.

Ça c'est une très bonne remarque, je vais retirer le hard-line-wrap

2021-04-27 11:50 UTC, Mesteery commented
> je vais retirer le hard-line-wrap
Ça rendra toutes les suggestions obsolètes 😥

2021-04-27 11:59 UTC, Julien00859 commented
> sur challenges

Tu donnes beaucoup d'importance aux challenges alors que ça n'a rien à voir...

2021-04-27 12:00 UTC, Mesteery commented
> 
> 
> > sur challenges
> 
> Tu donnes beaucoup d'importance aux challenges alors que ça n'a rien à voir...

Ok certes... Mais même en enlevant challenges de tous mes arguments, ils resteront valides.

2021-04-27 12:11 UTC, Julien00859 commented
On a utilisé "salon" parce que dans la documentation francophone de discord. Le terme "salon" est utilisé pour désigner les salons écrit. Le terme "canal" est utilisé pour désigner les salons vocaux. Il n'y a pas de débat à avoir, le terme correcte est donc bel et bien salon.

<https://support.discord.com/hc/fr/search>

> 112 résultats pour « salon » 

> 12 résultats pour « canal » ou « canaux » dans Toutes les catégories

2021-04-27 12:15 UTC, Mesteery commented
> On a utilisé "salon" parce que dans la documentation francophone de discord. Le terme "salon" est utilisé pour désigner les salons écrit. Le terme "canal" est utilisé pour désigner les salons vocaux.

d'accord et sur **ce** serveur ?? pour le canal s'appelle `#rejoindre-les-canaux` alors ? c'est un peu ridicule de dire "Allez voir le salon #rejoindre-les-canaux".

> Le terme "canal" est utilisé pour désigner les salons vocaux

ça par contre c'est complétement faux.

2021-04-27 12:25 UTC, Julien00859 commented
Je close pour ré-ouvrir propre

2021-04-27 12:25 UTC, closed without merging

2021-06-04 22:21 UTC, gordaxYTB commented
Ptdr y'a des fr c'est sensée être en anglais

2021-06-04 23:03 UTC, LeMinaw commented
![image](https://user-images.githubusercontent.com/3968360/120870670-2c16d600-c5a2-11eb-8652-70f07a2841e4.png)