Mise  à jour de la commande !ask
NotANameServer/discord pull request #45
Opened 2021-08-06 10:50 UTC by zazbone

Hello,

Une première proposition pour la commande `!ask` qui ne marche plus

J'ai vérifié au maximum (de mes petites capacitées) l'othographe et la syntaxe

J'ai jugé bon d'inclure:
 - (Un petit bonjour)
 - Pourquoi poser directement sa question ( sommairement le [Don't ask to ask, just ask](https://dontasktoask.com/) mais sans le sel)
 - Une listes que quelques recommandations basé sur mon resenti (Point principal à review)
 - Un rappel de la regle 1
 - Un rappel de :bellhop_bell: 

Je n'ai pas juger utile d'inclure
 - Un rappel de la commande `!code` (Je penses ouvrir une issue pour `!screenshot`)

Da bisous

2021-08-06 11:20 UTC, Mesteery commented
Il faut pas oublier d'ajouter ça dans https://github.com/NotANameServer/discord/blob/main/guidelines.md.

2021-08-06 11:24 UTC, zazbone commented
Ha oui,

Je peux commit et ajouter le commit à cette pr ou il faut que j'en ouvre une autre ?

2021-08-06 11:27 UTC, Mesteery commented on commandes-bots.md
> +Bonjour! Nous encourageons les utilisateurs du serveur à exposer directement leur problème dans les salons dédiés.
```suggestion
Bonjour ! Nous encourageons les utilisateurs du serveur à exposer directement leur problème dans les salons dédiés. 
```

2021-08-06 11:27 UTC, Mesteery commented on commandes-bots.md
> +Demander si quelqu'un connait telle ou telle technologie à peut de chance d'aboutir. Beaucoup de gens n'admette pas facilement si connaitre dans un domaine et d'autre n'apprécient pas de s'engager da
```suggestion
Demander si quelqu'un connait telle ou telle technologie à peu de chance d'aboutir. Beaucoup de gens n'admettent pas facilement s'y connaitre dans un domaine et d'autres n'apprécient pas de s'engager dans une discussion sans aucune information.
```
C'est ça que tu voulais dire ?

2021-08-06 11:27 UTC, Mesteery commented on commandes-bots.md
> +Ainsi il est préférable d'exposer le plus clairement possible sont problème sans attendre en y ajoutant le plus d'information possible:
```suggestion
Ainsi il est préférable d'exposer le plus clairement possible son problème sans attendre en y ajoutant le plus d'informations et de détails possible :
```

2021-08-06 11:27 UTC, Mesteery commented on commandes-bots.md
> +N'hésitez pas également à demander à être notifier lors d'une réponse (:bellhop:), le nombre de membre est très important mais tout le monde n'est pas connecté sans arrêt et les réponses peuvent arri
```suggestion
Aussi n'ayez pas peur de poser des questions qui vous paraissent bêtes, le respect des autres est primodial sur le serveur.
N'hésitez pas également à demander à être notifié lors d'une réponse (:bellhop_bell:), car les réponses peuvent arriver plus tard.
```

2021-08-06 11:27 UTC, Mesteery commented on commandes-bots.md
> + - Les demarches déjà menées pour essayer de résoudre le problème
Je ne pense pas que ce soit nécessaire de spécifier ça

2021-08-06 11:28 UTC, Mesteery commented
> Ha oui,
>
> Je peux commit et ajouter le commit à cette pr ou il faut que j'en ouvre une autre ?

Oui dans cette pr

2021-08-06 11:31 UTC, Mesteery commented on guidelines.md
> +
```suggestion
```

2021-08-06 11:31 UTC, Mesteery commented on guidelines.md
> +
```suggestion
```

2021-08-06 11:38 UTC, zazbone commented on commandes-bots.md
> +N'hésitez pas également à demander à être notifier lors d'une réponse (:bellhop:), le nombre de membre est très important mais tout le monde n'est pas connecté sans arrêt et les réponses peuvent arri
ya aussi un "r" à primo**r**dial
(Je sais pas comment ajouter la modif à ce fil XD)

2021-08-06 11:39 UTC, Mesteery commented on commandes-bots.md
> +N'hésitez pas également à demander à être notifier lors d'une réponse (:bellhop:), le nombre de membre est très important mais tout le monde n'est pas connecté sans arrêt et les réponses peuvent arri
c'est fait

2021-08-06 11:39 UTC, Mesteery commented
Aussi je pense que tu peux enlever le bonjour étant donné que ça part dans les guidelines et que ça fait un peu bizzare

2021-08-06 11:41 UTC, zazbone commented on commandes-bots.md
> + - Les demarches déjà menées pour essayer de résoudre le problème
Je penses au contraire que c'est l'intéret pricipale de la commande
Répondre aux:
<<Bonjour quelqu'un connais ...>>
 Mais aussi aux << Je comprend pas pourquoi ...marche pas>>

2021-08-06 11:44 UTC, zazbone commented
C'est vrai que c'est aussi la seul commande avec un bonjour
De mon coté j'aurai mis Bonjour à d'autre commande, donc c'est vrai que seul ça fait tache

2021-09-21 20:15 UTC, Equinox4 approved these changes

2021-09-24 21:39 UTC, Julien00859 commented
Rappelez moi de venir faire une contre-proposition ici demain

2021-09-24 21:42 UTC, Julien00859 commented
Aussi, pour info, parce que je suis noob et que j'avais oublié l'issue, voici la nouvelle commande !ask:

> Bonjour, il semblerait que la communauté ne comprend pas votre question. Êtes-vous sur d'avoir donné un maximum de détails ? Avec plus de détails (par exemple le code source et l'erreur complète) la communauté sera mieux armée pour comprendre votre problème et vous apporter son aide. Montrez vous bienveillant et patient et vous avez la garantie qu'un membre prendra le temps de vous aider.

Je suis entièrement disposé à ajouter un message différent dans les guidelines, je suis juste pas trop fan de la formulation ici dans la PR, demain je vous fait une contre-proposition si vous le voulez bien. Est-ce que pour la commande !ask vous êtes d'accord avec ce que j'ai config ? Ce sera ce qu'on décide ici qui sera la commande définitive, j'avais juste oublié l'issue.

2022-04-15 12:25 UTC, Elanis requested changes

2022-04-15 12:25 UTC, Elanis commented on commandes-bots.md
> +Demander si quelqu'un connait telle ou telle technologie à peut de chance d'aboutir. Beaucoup de gens n'admette pas facilement s'y connaitre dans un domaine et d'autre n'apprécient pas de s'engager d
```suggestion
Demander si quelqu'un connait telle ou telle technologie à peut de chance d'aboutir. Beaucoup de gens n'admettent pas facilement s'y connaitre dans un domaine et d'autre n'apprécient pas de s'engager dans une discussion sans aucune information.
```

2022-04-15 12:25 UTC, Elanis commented on commandes-bots.md
> + - La technologie utilisé (si possible un lien vers la documentation ou le site officiel)
```suggestion
 - La technologie utilisée (si possible un lien vers la documentation ou le site officiel)
```

2022-04-15 12:25 UTC, Elanis commented on commandes-bots.md
> + - Les demarches déjà menées pour essayer de résoudre le problème
```suggestion
 - Les démarches déjà menées pour essayer de résoudre le problème
```

2022-04-15 12:25 UTC, Elanis commented
(Ah bah j'avais oublié le dernier commentaire de Lazor, my bad)

2022-05-23 09:26 UTC, closed without merging