Guidelines: les mentions c'est chiant
NotANameServer/discord pull request #87
Opened 2022-03-11 12:26 UTC by Julien00859

J'ai été inspiré et j'ai écrit un long message, du coup je pense qu'on devrait proposer quelque chose d'autre pour `!ping` qqch de plus court.

2022-03-11 12:29 UTC, Elanis requested changes

2022-03-11 12:29 UTC, Elanis commented on guidelines.md
> +* interpeler un membre qui est reconnu comme expert d'un domaine lorsqu'il y a une question/un débat sur ce domain.
```suggestion
* interpeler un membre qui est reconnu comme expert d'un domaine lorsqu'il y a une question/un débat sur ce domaine.
```

2022-03-11 12:29 UTC, Elanis commented on guidelines.md
> +Quelques mauvaise raison:
```suggestion
Quelques mauvaises raisons:
```

2022-03-11 12:29 UTC, Elanis commented on guidelines.md
> +En ce qui concerne la fonctionnalité "répondre" de discord, celle-ci sert surtout à ramener un vieux message pour rétablir le contexte de la conversation. En ce sens, il est interdit d'utiliser "répo
J'aurais tendance à changer un peu ca, particulierement parce que c'est utile si on est dans une conversation bien active, ou tu sais pas si ton message va finir d'être écrit avant que les autres en aient mis entre deux.

2022-03-11 12:33 UTC, Julien00859 commented on guidelines.md
> +En ce qui concerne la fonctionnalité "répondre" de discord, celle-ci sert surtout à ramener un vieux message pour rétablir le contexte de la conversation. En ce sens, il est interdit d'utiliser "répo
Ouida, lorsqu'il y a des conversations qui s'intercalent souvent tu ne réponds pas au "dernier" message du salon (le dernier message était une autre conversation). Techniquement tu respectes la règle en utilisant "répondre" dans ce cas-là. Puis c'est une guideline, pas une règle, justement parce que ça invite à la nuance.

Si tu as une autre formulation à proposer je suis ouvert aux propositions :)

2022-03-11 12:35 UTC, Elanis commented on guidelines.md
> +En ce qui concerne la fonctionnalité "répondre" de discord, celle-ci sert surtout à ramener un vieux message pour rétablir le contexte de la conversation. En ce sens, il est interdit d'utiliser "répo
Je pense que ce serait mieux d'utiliser "inutile" plutôt que "interdit"

2022-03-11 13:19 UTC, Equinox4 requested changes

2022-03-11 13:19 UTC, Equinox4 commented on guidelines.md
> +* répondre à une question qui a été posée il y a longtemps (plus de 15 minutes) lorsque l'OP ne semble plus actif;
OP ?

2022-03-11 13:19 UTC, Equinox4 commented on guidelines.md
> +* interpeler un membre qui est reconnu comme expert d'un domaine lorsqu'il y a une question/un débat sur ce domain.
*domaine

2022-03-11 13:19 UTC, Equinox4 commented on guidelines.md
> +Quelques mauvaise raison:
*mauvaises raisons

2022-03-11 14:07 UTC, florentm35 commented on guidelines.md
> +* monopoliser l'attention d'un membre à outrance, par exemple pour que celui-ci réponde plus rapidement à un message.
Rajouter un petit rappel que le serveur n'est pas un SAV ?
monopoliser l'attention d'un membre à outrance, par exemple pour que celui-ci réponde plus rapidement à un message **, le serveur n'est pas votre SAV**.

2022-03-11 14:08 UTC, florentm35 commented on guidelines.md
> +* répondre à une question qui a été posée il y a longtemps (plus de 15 minutes) lorsque l'OP ne semble plus actif;
Peu être remplacer "l'OP" par "la personne", ça sera plus claire je pense

2022-03-11 15:25 UTC, Julien00859 commented
Yo les gars merci pour les reviews, si vous pouviez faire des "suggesting changes", ça me simplifierait beaucoup le vie :p

2022-03-11 15:27 UTC, Elanis commented on guidelines.md
> +En ce qui concerne la fonctionnalité "répondre" de discord, celle-ci sert surtout à ramener un vieux message pour rétablir le contexte de la conversation. En ce sens, il est interdit d'utiliser "répo
```suggestion
En ce qui concerne la fonctionnalité "répondre" de discord, celle-ci sert surtout à ramener un vieux message pour rétablir le contexte de la conversation. En ce sens, il est inutile d'utiliser "répondre" pour répondre au dernier message envoyé.
```

2022-03-11 16:07 UTC, florentm35 requested changes

2022-03-11 16:07 UTC, florentm35 commented on guidelines.md
> +* monopoliser l'attention d'un membre à outrance, par exemple pour que celui-ci réponde plus rapidement à un message.
```suggestion
* monopoliser l'attention d'un membre à outrance, par exemple pour que celui-ci réponde plus rapidement à un message , le serveur n'est pas votre SAV.
```

2022-03-11 16:07 UTC, florentm35 commented on guidelines.md
> +* répondre à une question qui a été posée il y a longtemps (plus de 15 minutes) lorsque l'OP ne semble plus actif;
```suggestion
* répondre à une question qui a été posée il y a longtemps (plus de 15 minutes) lorsque la personne ne semble plus actif;
```

2022-03-11 19:33 UTC, Elanis approved these changes

2022-03-11 19:38 UTC, Equinox4 approved these changes

2022-03-11 19:49 UTC, Karomy404 commented
Vous parlez meme pas du typs shift+reply du coup ?

2022-03-11 19:50 UTC, florentm35 commented
> Vous parlez meme pas du typs shift+reply du coup ?

Pour moi le message est déjà bien long et en plus ça ne fonctionne que sur les versions desktop et web

2022-03-21 15:09 UTC, Julien00859 commented
Ahah, j'ai trouvé pour !ping https://tenor.com/view/pings-off-reply-pings-off-reply-ping-discord-reply-ping-gif-22087396

2022-03-25 19:03 UTC, merged